title: "Sorachi Kato
theme: null

baseurl: "/dev-sora.github.io"
url: "https://dev-sora.github.io"

collections:
  publications:
    output: false

  software:
    output: false

  awards:
    output: false
